#################
### FONT/TEXT ###
#################

font_family FiraCode Nerd Font
text_composition_strategy legacy


##################
### APPEARANCE ###
##################

window_padding_width 2 6
background_opacity 0.95
include current-theme.conf


###################
### KEYBINDINGS ###
###################

clear_all_shortcuts no
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+up scroll_line_up
map ctrl+shift+down scroll_line_down


#####################
### MISCELLANEOUS ###
#####################

enable_audio_bell no

